//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BillPaymentEntities : DbContext
    {
        public BillPaymentEntities()
            : base("name=BillPaymentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<debit_creditcard_table> debit_creditcard_table { get; set; }
        public virtual DbSet<table_Registration> table_Registration { get; set; }
        public virtual DbSet<Operator_Table1> Operator_Table1 { get; set; }
        public virtual DbSet<PostPaid> PostPaids { get; set; }
        public virtual DbSet<PrePaid> PrePaids { get; set; }
        public virtual DbSet<table_Login> table_Login { get; set; }
    }
}
