//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator_Table1
    {
        public string Operator { get; set; }
        public decimal MRP { get; set; }
        public string ValidateDays { get; set; }
        public string Descriptions { get; set; }
        public string Roaming { get; set; }
        public string SMS { get; set; }
        public string DataSpeed { get; set; }
    }
}
