//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrePaid
    {
        public long MobileNumber { get; set; }
        public string Operator { get; set; }
    
        public virtual table_Registration table_Registration { get; set; }
    }
}
