//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_Registration
    {
        public string CustomerName { get; set; }
        public long MobileNumber { get; set; }
        public string EmailID { get; set; }
        public string Plantype { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public string NewPassword { get; set; }
        public string ConfirmPassword { get; set; }
        public string Operator { get; set; }
    
        public virtual PostPaid PostPaid { get; set; }
        public virtual PrePaid PrePaid { get; set; }
        public virtual table_Login table_Login { get; set; }
    }
}
